### PR TITLE
fixed deprecated x86 ndlls

### PR DESCRIPTION
**Pull request by Neu2o**
- only build host architecture for mac (like linux now)
- avoid building binaries when "-nocffi" is specified (was like this when rebuilding tools, but never for the initial build)
- optional: rebuild linux x64 binaries when "rebuild" is specified (like mac x86/x64 and linux x86 now)

### CODE REVIEW

**Comment by nadako** [comment]
Since we don't really use _any_ functionality of the lime build tools, besides haxe compiler invocation, I was thinking about just making simple hxml file(s) for building foe/html, completely skipping lime...

**Comment by Neu2o** [comment]
I know you prepared this already, still I think it's ok to have lime fixed and to keep support for the regular build system, no matter if we move away from it sooner or later. The effort was not big and for now it helps.

**Comment by nadako** [comment]
Yeah, I'm not against the fix of course :) It just reminded me about my "plan" and I just wanted to hear your opinion on that.

**Comment by Neu2o** [comment]
I like your idea for sure, there is quite some overhead around the lime build system, so getting rid of it makes sense to me. As soon as you are back, we should try it again ;)

**Pull request merged**
